package com.example.ui.components

object AppStrings {
    data class LocalizedStrings(
        val welcomeBack: String,
        val signInSubtitle: String,
        val emailOrPhone: String,
        val password: String,
        val forgotPassword: String,
        val signUp: String,
        val signIn: String,
        val guestDemo: String,
        val dontHaveAccount: String,
        val navHome: String,
        val navMap: String,
        val navAlerts: String,
        val navReports: String,
        val navProfile: String,
        val titleLandslide: String,
        val subtitleEarlyWarning: String,
        val tagline: String,
        val riskLevel: String,
        val riskScore: String,
        val critical: String,
        val watch: String,
        val normal: String,
        val offline: String,
        val landslideDetected: String,
        val heavyRainfall: String,
        val northEastRegion: String,
        val zoneDetails: String,
        val shapExplanation: String,
        val reportIncident: String,
        val myReports: String,
        val offlineMode: String,
        val syncStatus: String
    )

    private val en = LocalizedStrings(
        welcomeBack = "WELCOME BACK",
        signInSubtitle = "Sign in to continue to a safer tomorrow",
        emailOrPhone = "Email or Phone number",
        password = "Password",
        forgotPassword = "Forgot password?",
        signUp = "Sign Up",
        signIn = "Sign In",
        guestDemo = "Explore Demo",
        dontHaveAccount = "Don't have an account ? Sign up",
        navHome = "Home",
        navMap = "Map",
        navAlerts = "Alerts",
        navReports = "Reports",
        navProfile = "Profile",
        titleLandslide = "LANDSLIDE",
        subtitleEarlyWarning = "EARLY WARNING SYSTEM",
        tagline = "Monitor • Predict • Respond",
        riskLevel = "Risk Level",
        riskScore = "Risk Score",
        critical = "Critical",
        watch = "Watch",
        normal = "Normal",
        offline = "Offline",
        landslideDetected = "LANDSLIDE DETECTED",
        heavyRainfall = "Heavy Rainfall",
        northEastRegion = "North East Region",
        zoneDetails = "Zone Details",
        shapExplanation = "View SHAP Explanation",
        reportIncident = "Report Incident",
        myReports = "My Reports",
        offlineMode = "Offline Mode",
        syncStatus = "Sync Status"
    )

    private val hi = LocalizedStrings(
        welcomeBack = "स्वागत हे",
        signInSubtitle = "सुरक्षित कल के लिए साइन इन करें",
        emailOrPhone = "ईमेल या फ़ोन नंबर",
        password = "पासवर्ड",
        forgotPassword = "पासवर्ड भूल गए?",
        signUp = "साइन अप करें",
        signIn = "साइन इन करें",
        guestDemo = "डेमो देखें",
        dontHaveAccount = "खाता नहीं है? साइन अप करें",
        navHome = "होम",
        navMap = "मानचित्र",
        navAlerts = "अलर्ट",
        navReports = "रिपोर्ट",
        navProfile = "प्रोफ़ाइल",
        titleLandslide = "भूस्खलन",
        subtitleEarlyWarning = "पूर्व चेतावनी प्रणाली",
        tagline = "निगरानी • पूर्वानुमान • प्रतिक्रिया",
        riskLevel = "जोखिम स्तर",
        riskScore = "जोखिम स्कोर",
        critical = "गंभीर",
        watch = "निगरानी",
        normal = "सामान्य",
        offline = "ऑफ़लाइन",
        landslideDetected = "भूस्खलन का पता चला",
        heavyRainfall = "भारी वर्षा",
        northEastRegion = "पूर्वोत्तर क्षेत्र",
        zoneDetails = "क्षेत्र विवरण",
        shapExplanation = "SHAP व्याख्या देखें",
        reportIncident = "घटना रिपोर्ट करें",
        myReports = "मेरी रिपोर्ट",
        offlineMode = "ऑफ़लाइन मोड",
        syncStatus = "सिंक स्थिति"
    )

    private val bn = LocalizedStrings(
        welcomeBack = "স্বাগতম",
        signInSubtitle = "নিরাপদ আগামী দিনের জন্য সাইন ইন করুন",
        emailOrPhone = "ইমেল বা ফোন নম্বর",
        password = "পাসওয়ার্ড",
        forgotPassword = "পাসওয়ার্ড ভুলে গেছেন?",
        signUp = "সাইন আপ করুন",
        signIn = "সাইন ইন করুন",
        guestDemo = "ডেমো দেখুন",
        dontHaveAccount = "অ্যাকাউন্ট নেই? সাইন আপ করুন",
        navHome = "হোম",
        navMap = "মানচিত্র",
        navAlerts = "সতর্কতা",
        navReports = "রিপোর্ট",
        navProfile = "প্রোফাইল",
        titleLandslide = "ভূমিধস",
        subtitleEarlyWarning = "পূর্ব সতর্কীকরণ ব্যবস্থা",
        tagline = "নজরদারি • পূর্বাভাস • প্রতিক্রিয়া",
        riskLevel = "ঝুঁকির মাত্রা",
        riskScore = "ঝুঁকির স্কোর",
        critical = "মারাত্মক",
        watch = "নজরদারিতে",
        normal = "স্বাভাবিক",
        offline = "অফলাইন",
        landslideDetected = "ভূমিধস শনাক্ত হয়েছে",
        heavyRainfall = "ভারী বৃষ্টিপাত",
        northEastRegion = "উত্তর-পূর্ব অঞ্চল",
        zoneDetails = "অঞ্চলের বিবরণ",
        shapExplanation = "SHAP ব্যাখ্যা দেখুন",
        reportIncident = "ঘটনা রিপোর্ট করুন",
        myReports = "আমার রিপোর্ট",
        offlineMode = "অফলাইন মোড",
        syncStatus = "সিঙ্ক স্থিতি"
    )

    private val asLang = LocalizedStrings(
        welcomeBack = "স্বাগতম",
        signInSubtitle = "সুৰক্ষিত ভৱিষ্যতৰ বাবে চাইন ইন কৰক",
        emailOrPhone = "ইমেইল বা ফোন নম্বৰ",
        password = "পাছৱৰ্ড",
        forgotPassword = "পাছৱৰ্ড পাহৰিলে?",
        signUp = "চাইন আপ কৰক",
        signIn = "চাইন ইন কৰক",
        guestDemo = "ডেমো চাওক",
        dontHaveAccount = "একাউণ্ট নাই? চাইন আপ কৰক",
        navHome = "গৃহ",
        navMap = "মানচিত্ৰ",
        navAlerts = "সতৰ্কবাৰ্তা",
        navReports = "প্ৰতিবেদন",
        navProfile = "প্ৰফাইল",
        titleLandslide = "ভূমিস্খলন",
        subtitleEarlyWarning = "আগতীয়া সতৰ্কবাৰ্তা ব্যৱস্থা",
        tagline = "নিৰীক্ষণ • ভৱিষ্যদ্বাণী • সঁহাৰি",
        riskLevel = "বিপদৰ মাত্ৰা",
        riskScore = "বিপদৰ স্ক'ৰ",
        critical = "সংকটজনক",
        watch = "নজৰত",
        normal = "সাধাৰণ",
        offline = "অফলাইন",
        landslideDetected = "ভূমিস্খলন ধৰা পৰিছে",
        heavyRainfall = "প্ৰৱল বৰষুণ",
        northEastRegion = "উত্তৰ-পূব অঞ্চল",
        zoneDetails = "অঞ্চলৰ বিৱৰণ",
        shapExplanation = "SHAP ব্যাখ্যা চাওক",
        reportIncident = "ঘটনা প্ৰতিবেদন দাখিল কৰক",
        myReports = "মোৰ প্ৰতিবেদনসমূহ",
        offlineMode = "অফলাইন ম'ড",
        syncStatus = "চিঙ্ক স্থিতি"
    )

    fun get(code: String): LocalizedStrings = when (code) {
        "hi" -> hi
        "bn" -> bn
        "as" -> asLang
        else -> en
    }
}
